// Dados do portfólio — imagens em assents/img/
window.PORTFOLIO_PHOTOS = [
  {
    id: 1,
    title: "Ritual de Corpo e Axé",
    category: "Candomblé",
    description: "Registro realizado com autorização durante ritual fechado.",
    image: "assents/img/rituais.jpeg",
  },
  {
    id: 2,
    title: "Canto e Devoção",
    category: "Candomblé",
    description: "Momento de canto e oferenda em terreiro.",
    image: "assents/img/canto-devocao.jpeg",
  },
  {
    id: 3,
    title: "Linha do Candomblé",
    category: "Candomblé",
    description: "Trabalho espiritual em gira.",
    image: "assents/img/linha-camdomble.jpeg",
  },
  {
    id: 4,
    title: "Força e Ancestralidade",
    category: "Quimbanda",
    description: "Registro com consentimento dos participantes.",
    image: "assents/img/forca%20e%20ancestralidade.jpeg",
  },
  {
    id: 5,
    title: "Retrato Ancestral",
    category: "Retratos Ancestrais",
    description: "Retrato em contexto de respeito e memória.",
    image: "assents/img/retrato-ancestral.jpeg",
  },
  {
    id: 6,
    title: "Memória e Presença",
    category: "Rituais e Festas",
    description: "Registro de momento sagrado.",
    image: "assents/img/4.jpeg",
  },
  {
    id: 7,
    title: "Axé e Devoção",
    category: "Candomblé",
    description: "Fotografia documental com respeito.",
    image: "assents/img/8.jpeg",
  },
  {
    id: 8,
    title: "Terreiro",
    category: "Rituais e Festas",
    description: "Celebração e comunidade.",
    image: "assents/img/12.jpeg",
  },
  {
    id: 9,
    title: "Sagrado e Ancestral",
    category: "Retratos Ancestrais",
    description: "Registro com consentimento e presença.",
    image: "assents/img/carrosel.jpeg",
  },
  {
    id: 10,
    title: "Corpo e Ritual",
    category: "Candomblé",
    description: "Momento de ritual registrado com axé.",
    image: "assents/img/carrosel2.jpeg",
  },
  {
    id: 11,
    title: "No terreiro",
    category: "Rituais e Festas",
    description: "Registro com respeito e presença.",
    image: "assents/img/5.jpeg",
  },
  {
    id: 12,
    title: "Ancestralidade",
    category: "Retratos Ancestrais",
    description: "Memória do sagrado.",
    image: "assents/img/6.jpeg",
  },
  {
    id: 13,
    title: "Ritual e axé",
    category: "Candomblé",
    description: "Fotografia documental.",
    image: "assents/img/7.jpeg",
  },
  {
    id: 14,
    title: "Presença",
    category: "Rituais e Festas",
    description: "Registro com consentimento.",
    image: "assents/img/9.jpeg",
  },
  {
    id: 15,
    title: "Sagrado",
    category: "Candomblé",
    description: "Momento de devoção.",
    image: "assents/img/10.jpeg",
  },
  {
    id: 16,
    title: "Memória viva",
    category: "Retratos Ancestrais",
    description: "Registro com axé.",
    image: "assents/img/11.jpeg",
  },
  {
    id: 17,
    title: "Terreiro e comunidade",
    category: "Rituais e Festas",
    description: "Celebração e espiritualidade.",
    image: "assents/img/13.jpeg",
  },
  {
    id: 18,
    title: "Corpo em ritual",
    category: "Candomblé",
    description: "Fotografia com respeito.",
    image: "assents/img/14.jpeg",
  },
  {
    id: 19,
    title: "Devoção",
    category: "Retratos Ancestrais",
    description: "Registro documental.",
    image: "assents/img/15.jpeg",
  },
  {
    id: 20,
    title: "Axé",
    category: "Rituais e Festas",
    description: "Memória do sagrado e da ancestralidade.",
    image: "assents/img/16.jpeg",
  },
  {
    id: 21,
    title: "Registro",
    category: "Rituais e Festas",
    description: "Fotografia documental com respeito.",
    image: "assents/img/WhatsApp%20Image%202026-04-07%20at%2022.14.52.jpeg",
  },
  {
    id: 22,
    title: "Presença",
    category: "Candomblé",
    description: "Registro com axé.",
    image: "assents/img/WhatsApp%20Image%202026-04-07%20at%2022.14.52%20(1).jpeg",
  },
  {
    id: 23,
    title: "Terreiro",
    category: "Rituais e Festas",
    description: "Memória viva.",
    image: "assents/img/WhatsApp%20Image%202026-04-07%20at%2022.14.53.jpeg",
  },
  {
    id: 24,
    title: "Devoção",
    category: "Retratos Ancestrais",
    description: "Registro com consentimento.",
    image: "assents/img/WhatsApp%20Image%202026-04-07%20at%2022.14.54.jpeg",
  },
  {
    id: 25,
    title: "Ritual",
    category: "Candomblé",
    description: "Fotografia com sensibilidade.",
    image: "assents/img/WhatsApp%20Image%202026-04-07%20at%2022.14.56.jpeg",
  },
  {
    id: 26,
    title: "Comunidade",
    category: "Rituais e Festas",
    description: "Celebração e espiritualidade.",
    image: "assents/img/WhatsApp%20Image%202026-04-07%20at%2022.14.57.jpeg",
  },
  {
    id: 27,
    title: "Ancestralidade",
    category: "Retratos Ancestrais",
    description: "Memória do sagrado.",
    image: "assents/img/WhatsApp%20Image%202026-04-07%20at%2022.14.59.jpeg",
  },
  {
    id: 28,
    title: "Axé e corpo",
    category: "Candomblé",
    description: "Registro documental.",
    image: "assents/img/WhatsApp%20Image%202026-04-07%20at%2022.15.01.jpeg",
  },
  {
    id: 29,
    title: "Momento sagrado",
    category: "Rituais e Festas",
    description: "Presença e respeito.",
    image: "assents/img/WhatsApp%20Image%202026-04-07%20at%2022.15.02.jpeg",
  },
  {
    id: 30,
    title: "Memória",
    category: "Retratos Ancestrais",
    description: "História e fé.",
    image: "assents/img/WhatsApp%20Image%202026-04-07%20at%2022.15.03.jpeg",
  },
  {
    id: 31,
    title: "Espiritualidade",
    category: "Candomblé",
    description: "Registro com axé.",
    image: "assents/img/WhatsApp%20Image%202026-04-07%20at%2022.15.05.jpeg",
  },
  {
    id: 32,
    title: "Celebração",
    category: "Rituais e Festas",
    description: "Terreiro e comunidade.",
    image: "assents/img/WhatsApp%20Image%202026-04-07%20at%2022.15.09.jpeg",
  },
  {
    id: 33,
    title: "Sagrado",
    category: "Retratos Ancestrais",
    description: "Fotografia com verdade.",
    image: "assents/img/WhatsApp%20Image%202026-04-07%20at%2022.15.09%20(1).jpeg",
  },
];

window.PORTFOLIO_CATEGORIES = [
  "Todos",
  "Candomblé",
  "Umbanda",
  "Quimbanda",
  "Retratos Ancestrais",
  "Rituais e Festas",
];
